import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import type { MessageType, MessagesState, PiiMapping } from "../types";

const initialState: MessagesState = {
  messageList: [],
  piiMappingList: [],
};

const messagesSlice = createSlice({
  name: "messages",
  initialState,
  reducers: {
    addMessage: (state, action: PayloadAction<Omit<MessageType, "id">>) => {
      // If the message is from the assistant, it is a response to a user message, thus we need to store the user message id
      if (
        action.payload.sender === "assistant" &&
        !action.payload.userMessageId
      ) {
        throw new Error("userMessageId is required for assistant messages");
      }
      state.messageList.push({
        id: state.messageList.length + 1,
        // the uuid generated by the client
        messageId: action.payload.messageId,
        // user message id that the message is a response to
        userMessageId: action.payload.userMessageId,
        content: action.payload.content,
        sender: action.payload.sender,
      });
    },
    storePiiMapping: (
      state,
      action: PayloadAction<{ messageId: string; mapping: PiiMapping }>,
    ) => {
      // checks that the messageId exists in the messageList and has a sender "user"
      const userMessage = state.messageList.find(
        (message) =>
          message.messageId === action.payload.messageId &&
          message.sender === "user",
      );
      if (!userMessage) {
        throw new Error("User message not found");
      }
      state.piiMappingList.push({
        id: state.piiMappingList.length + 1,
        // The uuid of the user message that the mapping belongs to
        messageId: action.payload.messageId,
        mapping: action.payload.mapping,
      });
    },
  },
});

export const { addMessage, storePiiMapping } = messagesSlice.actions;
export default messagesSlice.reducer;
